import Providers from '@/components/Providers'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'
import { Toaster } from '@/components/ui/toaster'
import Navbar from '@/components/layout/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body className={inter.className}>
      <div className=" fixed bottom-[5rem] -z-10 left-[-35rem] h-[25rem] w-[40rem] rounded-full blur-[10rem] sm:w-[40rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem] bg-[#b9b3ff]  dark:bg-[#292180] opacity-50"></div>
      <div className=" fixed top-[15rem] -z-10 right-[35rem] h-[25rem] w-[40rem] rounded-full blur-[10rem] sm:w-[40rem] md:right-[-33rem] lg:right-[-28rem] xl:right-[-15rem] 2xl:right-[-5rem] bg-[#b9b3ff]  dark:bg-[#292180] opacity-75"></div>
      <Providers>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          <main className="flex min-h-screen flex-col items-center justify-between p-24">
            {children}
          </main>
          <Toaster />
        </ThemeProvider>
      </Providers>
    </body>
  </html>
  )
}
